Vagrant.configure("2") do |config|
  #This is a global setting which will execute "echo Hello" command in both Vm.
  #config.vm.provision "shell", inline: "echo Hello"

  # Machine for Web Server
  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/bionic64"
    web1.vm.network "private_network", ip: "192.168.33.26"
    web1.vm.network "public_network"
    web1.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 2
    end
    web1.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install apache2 wget unzip -y
        systemctl start apache2
        systemctl enable apache2
        cd /tmp/
        wget https://www.tooplate.com/zip-templates/2119_gymso_fitness.zip
        unzip -o 2119_gymso_fitness.zip
        cp -r 2119_gymso_fitness/* /var/www/html/
        systemctl restart apache2
    SHELL
  end
# Machine for Database Server 
  config.vm.define "db1" do |db1|
    db1.vm.box = "geerlingguy/centos7"
    db1.vm.network "private_network", ip: "192.168.33.22"
    db1.vm.network "public_network"
    db1.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 2
    end
    db1.vm.provision "shell", inline: <<-SHELL
      yum install mariadb-server -y
      systemctl start mariadb
      systemctl enable mariadb
    SHELL
  end
end